name: In Out
on: 
  issue_comment:
    types: [created]
jobs: 
  generate_static_html_files:
    if: ${{ github.event.issue.title == 'InOut' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The comment is ${{ github.event.comment.body }}"
      - run: echo "The user is ${{ github.event.sender.login }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - run: python ${{ github.workspace }}/main.py --message '${{ github.event.comment.body }}' --local_repo_path '${{ github.workspace }}'
      - run: |
          git config --local user.email "skycs608@gmail.com"
          git config --local user.name "skycs608"
          git remote set-url origin https://skycs608:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "Generated static files"
          git push origin master
